using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;

namespace PhotoOrganizer
{
    public class SharedConstants
    {
        public enum EXIFData
        {
            Unknown,
            [Description("/app0")]
            App0,
            [Description("/app0/{ushort=0}")]
            Version,
            [Description("/app0/{ushort=1}")]
            Units,
            [Description("/app0/{ushort=2}")]
            DpiX,
            [Description("/app0/{ushort=3}")]
            DpiY,
            [Description("/app0/{ushort=4}")]
            Xthumbnail,
            [Description("/app0/{ushort=5}")]
            Ythumbnail,
            [Description("/app0/{ushort=6}")]
            ThumbnailData,
            [Description("/app1")]
            App1,
            [Description("/app1/ifd/ or /app1/{ushort=0}")]
            ZeroIFD,
            [Description("/app1/ifd/exif or /app1/ifd/{ushort=34665}")]
            EXIFIFD,
            [Description("/app1/thumb/ or /app1/{ushort=1}")]
            ThumbnailIFD,
            [Description("/app13")]
            App13,
            [Description("/app13/irb or /app13/{ushort=0}")]
            IRB,
            [Description("/app13/irb/{ulonglong=*} where * = IRB Identifier (see IRB spec)")]
            IRBEntry,
            [Description("/app13/irb/{ulonglong=*}/{}")]
            IRBEntryContents,
            [Description("/app13/irb/8bimiptc or /app13/irb/{ulonglong=61857348781060}")]
            EightBIMIPTC,
            [Description("/app13/irb/8bimiptc/iptc")]
            IPTC,
            [Description("/app13/irb/8bimiptc/iptc/{str=*}")]
            IPTCEntry,
            [Description("/app13/irb/8bimResInfo or /app13/irb/{ulonglong=61857348781037}")]
            EightBIMResolutionInfo,
            [Description("/com")]
            JPEGComment,
            [Description("/luminance")]
            Luminance,
            [Description("/chrominance")]
            Chrominance,
            [Description("/xmp")]
            XMP,
            [Description("/{ushort=256}")]
            ImageWidth,
            [Description("/{ushort=257}")]
            ImageLength,
            [Description("/{ushort=258}")]
            BitsPerSample,
            [Description("/{ushort=259}")]
            Compression,
            [Description("/{ushort=262}")]
            PhotometricInterpretation,
            [Description("/{ushort=274}")]
            Orientation,
            [Description("/{ushort=277}")]
            SamplesPerPixel,
            [Description("/{ushort=284}")]
            PlanarConfiguration,
            [Description("/{ushort=530}")]
            YCbCrSubSampling,
            [Description("/{ushort=531}")]
            YCbCrPositioning,
            [Description("/{ushort=282}")]
            XResolution,
            [Description("/{ushort=283}")]
            YResolution,
            [Description("/{ushort=296}")]
            ResolutionUnit,
            [Description("/{ushort=306}")]
            DateTime,
            [Description("/{ushort=270}")]
            ImageDescription,
            [Description("/{ushort=271}")]
            Make,
            [Description("/{ushort=272}")]
            Model,
            [Description("/{ushort=305}")]
            Software,
            [Description("/{ushort=315}")]
            Artist,
            [Description("/{ushort=33432}")]
            Copyright,
            [Description("/{ushort=338}")]
            ExtraSamples,
            [Description("/{ushort=254}")]
            NewSubfileType,
            [Description("/{ushort=278}")]
            RowsPerStrip,
            [Description("/{ushort=279}")]
            StripByteCounts,
            [Description("/{ushort=273}")]
            StripOffsets,
            [Description("/{ushort=36864}")]
            ExifVersion,
            [Description("/{ushort=40960}")]
            FlashpixVersion,
            [Description("/{ushort=40961}")]
            ColorSpace,
            [Description("/{ushort=40962}")]
            PixelXDimension,
            [Description("/{ushort=40963}")]
            PixelYDimension,
            [Description("/{ushort=37500}")]
            MakerNote,
            [Description("/{ushort=37510}")]
            UserComment,
            [Description("/{ushort=36867}")]
            DateTimeOriginal,
            [Description("/{ushort=36868}")]
            DateTimeDigitized,
            [Description("/{ushort=42016}")]
            ImageUniqueID,
            [Description("/{ushort=42032}")]
            CameraOwnerName,
            [Description("/{ushort=42033}")]
            BodySerialNumber,
            [Description("/{ushort=42034}")]
            LensSpecification,
            [Description("/{ushort=42035}")]
            LensMake,
            [Description("/{ushort=42036}")]
            LensModel,
            [Description("/{ushort=42037}")]
            LensSerialNumber,
            [Description("/{ushort=33434}")]
            ExposureTime,
            [Description("/{ushort=33437}")]
            FNumber,
            [Description("/{ushort=34850}")]
            ExposureProgram,
            [Description("/{ushort=34852}")]
            SpectralSensitivity,
            [Description("/{ushort=34855}")]
            PhotographicSensitivity,
            [Description("/{ushort=34856}")]
            OECF,
            [Description("/{ushort=34864}")]
            SensitivityType,
            [Description("/{ushort=34865}")]
            StandardOutputSensitivity,
            [Description("/{ushort=34866}")]
            RecommendedExposureIndex,
            [Description("/{ushort=34867}")]
            ISOSpeed,
            [Description("/{ushort=34868}")]
            ISOSpeedLatitudeyyy,
            [Description("/{ushort=34869}")]
            ISOSpeedLatitudezzz,
            [Description("/{ushort=37377}")]
            ShutterSpeedValue,
            [Description("/{ushort=37378}")]
            ApertureValue,
            [Description("/{ushort=37379}")]
            BrightnessValue,
            [Description("/{ushort=37380}")]
            ExposureBiasValue,
            [Description("/{ushort=37381}")]
            MaxApertureValue,
            [Description("/{ushort=37382}")]
            SubjectDistance,
            [Description("/{ushort=37383}")]
            MeteringMode,
            [Description("/{ushort=37384}")]
            LightSource,
            [Description("/{ushort=37385}")]
            Flash,
            [Description("/{ushort=37386}")]
            FocalLength,
            [Description("/{ushort=37396}")]
            SubjectArea,
            [Description("/{ushort=41483}")]
            FlashEnergy,
            [Description("/{ushort=41484}")]
            SpatialFrequencyResponse,
            [Description("/{ushort=41486}")]
            FocalPlaneXResolution,
            [Description("/{ushort=41487}")]
            FocalPlaneYResolution,
            [Description("/{ushort=41488}")]
            FocalPlaneResolutionUnit,
            [Description("/{ushort=41492}")]
            SubjectLocation,
            [Description("/{ushort=41493}")]
            ExposureIndex,
            [Description("/{ushort=41495}")]
            SensingMethod,
            [Description("/{ushort=41728}")]
            FileSource,
            [Description("/{ushort=41729}")]
            SceneType,
            [Description("/{ushort=41730}")]
            CFAPattern,
            [Description("/{ushort=41985}")]
            CustomRendered,
            [Description("/{ushort=41986}")]
            ExposureMode,
            [Description("/{ushort=41987}")]
            WhiteBalance,
            [Description("/{ushort=41988}")]
            DigitalZoomRatio,
            [Description("/{ushort=41989}")]
            FocalLengthIn35mmFilm,
            [Description("/{ushort=41990}")]
            SceneCaptureType,
            [Description("/{ushort=41991}")]
            GainControl,
            [Description("/{ushort=41992}")]
            Contrast,
            [Description("/{ushort=41993}")]
            Saturation,
            [Description("/{ushort=41994}")]
            Sharpness,
            [Description("/{ushort=41995}")]
            DeviceSettingDescription,
            [Description("/{ushort=41996}")]
            SubjectDistanceRange,
            [Description("{ushort=0}")]
            GPSVersionID,
            [Description("{ushort=1}")]
            GPSLatitudeRef,
            [Description("{ushort=2}")]
            GPSLatitude,
            [Description("{ushort=3}")]
            GPSLongitudeRef,
            [Description("{ushort=4}")]
            GPSLongitude,
            [Description("{ushort=5}")]
            GPSAltitudeRef,
            [Description("{ushort=6}")]
            GPSAltitude,
            [Description("{ushort=7}")]
            GPSTimeStamp,
            [Description("{ushort=8}")]
            GPSSatellites,
            [Description("{ushort=9}")]
            GPSStatus,
            [Description("{ushort=10}")]
            GPSMeasureMode,
            [Description("{ushort=11}")]
            GPSDOP,
            [Description("{ushort=12}")]
            GPSSpeedRef,
            [Description("{ushort=13}")]
            GPSSpeed,
            [Description("{ushort=14}")]
            GPSTrackRef,
            [Description("{ushort=15}")]
            GPSTrack,
        }
    }
}
